### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ghost** [devopsext/esni-rev-proxy#1]
when I type `go build` after I have everything done, I got this message:

```
.GOROOT/src/net/http/response.go:169:29: too many arguments to conversion to badStringError: badStringError("malformed HTTP response", line)
.GOROOT/src/net/http/response.go:179:29: too many arguments to conversion to badStringError: badStringError("malformed HTTP status code", statusCode)
.GOROOT/src/net/http/response.go:183:29: too many arguments to conversion to badStringError: badStringError("malformed HTTP status code", statusCode)
.GOROOT/src/net/http/response.go:187:29: too many arguments to conversion to badStringError: badStringError("malformed HTTP version", resp.Proto)
.GOROOT/src/net/http/transfer.go:313:26: too many arguments to conversion to badStringError: badStringError("invalid Trailer key", k)
.GOROOT/src/net/http/transfer.go:780:26: too many arguments to conversion to badStringError: badStringError("bad trailer key", key)
.GOROOT/src/net/http/transfer.go:1044:27: too many arguments to conversion to badStringError: badStringError("bad Content-Length", cl)
.GOROOT/src/net/http/transport.go:538:29: too many arguments to conversion to badStringError: badStringError("unsupported protocol scheme", scheme)
```

It seems like a problem, how can I deal with it?

**Comment by i-prudnikov** [comment]
Hello, sorry for late response, seems that I didn't receive any notifications from github.
Which version of GO your are using?
I see that I forgot to mention that I've tested the custom GOROOT preparation only against golang 1.13. The issue you are reporting most probably connected with the version of golang.

**Comment by ghost** [comment]
Hahaha, that's a really long time, but never mind.
It's [reported](https://gfw.report/blog/gfw_esni_blocking/en/) that China has blocked of TLS connections with the encrypted SNI (ESNI) extension which makes me very annoyed.
And actually I forget what I've done in August and I'm no familiar with the Golang.
Thank's for you reply, and this is a really awesome repo since the run-of-the-mill web servers are rarely support with ESNI.
