### ISSUE TITLE
Error while running prepareGoRoot.sh

### ISSUE THREAD

**Issue by dhruvrauthan** [devopsext/esni-rev-proxy#2]
Hey,

I was trying to enable ESNI on my Apache web server and wanted to use this repository to get closer to my goal. However, when I try to run the prepareGoRoot.sh script it gives an error:

```
cp: target './.GOROOT/src/' is not a directory
```

I can't figure out the error and would be grateful if you could look into it. @i-prudnikov 

Cheers

**Comment by i-prudnikov** [comment]
Hey @dhruvrauthan, let's try to figure it out.
First you need to build it against go 1.13. I think It would work also with more recent versions but I didn't check it against that.
So far it is not clear what cause this issue, let's add debugging into the `prepareGoRoot.sh`.
Please use this script instead the one that comes from repo, and paste here the results:
```bash
#!/bin/sh
goRoot=$(go env GOROOT)
goHostOS=$(go env GOHOSTOS)
goHostArch=$(go env GOHOSTARCH)
installRace=$(go env CGO_ENABLED)

localGoRoot="$1"
if [ -z "$localGoRoot" ]; then
  localGoRoot="./.GOROOT"
fi

patchSrc="./.patch/src"

mkdir -p ${localGoRoot}

echo "Reporting variables"
echo "goRoot => '$goRoot'"
echo "goHostOS => '$goHostOS'"
echo "goHostArch => '$goHostArch'"
echo "installRace => '$installRace'"
echo "localGoRoot => '$localGoRoot'"
echo "==============="

#Setting up bin
if [ ! -d ${localGoRoot}/bin ]; then
	ln -s ${goRoot}/bin ${localGoRoot}/bin
fi

#src + patch
cp -r ${goRoot}/src ${localGoRoot}/
rm -rf ${localGoRoot}/src/crypto/tls #Should be fully rebuilt

#patching src
cp -rf ${patchSrc}/* ${localGoRoot}/src/

#pkg:
mkdir -p ${localGoRoot}/pkg
cp -rf ${goRoot}/pkg/${goHostOS}_${goHostArch} ${localGoRoot}/pkg/

#Removing outdated object files to be rebuilt
rm -rf ${localGoRoot}/pkg/${goHostOS}_${goHostArch}/crypto/tls.a
rm -rf ${localGoRoot}/pkg/${goHostOS}_${goHostArch}/net/http*

if [ $installRace -eq "1" ]; then
  if [ -d "${goRoot}/pkg/${goHostOS}_${goHostArch}_race" ]; then
	  cp -rf ${goRoot}/pkg/${goHostOS}_${goHostArch}_race ${localGoRoot}/pkg/
	fi
	rm -rf ${localGoRoot}/pkg/${goHostOS}_${goHostArch}_race/crypto/tls.a
	rm -rf ${localGoRoot}/pkg/${goHostOS}_${goHostArch}_race/net/http*
fi

if [ ! -d ${localGoRoot}/pkg/include ]; then
	ln -s ${goRoot}/pkg/include ${localGoRoot}/pkg/include
fi

if [ ! -d ${localGoRoot}/pkg/tool ]; then
	ln -s ${goRoot}/pkg/tool ${localGoRoot}/pkg/tool
	#cp -rf ${goRoot}/pkg/tool ${localGoRoot}/pkg/
fi
```

Expected content of `.GOROOT` should be (example from my mac):
```
esni-rev-proxy (master) $ tree -L 2 ./.GOROOT/
./.GOROOT/
├── bin -> /usr/local/Cellar/go/1.13.1/libexec/bin
├── pkg
│   ├── darwin_amd64
│   ├── darwin_amd64_race
│   ├── include -> /usr/local/Cellar/go/1.13.1/libexec/pkg/include
│   └── tool -> /usr/local/Cellar/go/1.13.1/libexec/pkg/tool
└── src
    ├── Make.dist
    ├── README.vendor
    ├── all.bash
    ├── all.bat
    ├── all.rc
    ├── archive
    ├── bootstrap.bash
    ├── bufio
    ├── buildall.bash
    ├── builtin
    ├── bytes
    ├── clean.bash
    ├── clean.bat
    ├── clean.rc
    ├── cmd
    ├── cmp.bash
    ├── compress
    ├── container
    ├── context
    ├── crypto
    ├── database
    ├── debug
    ├── encoding
    ├── errors
    ├── expvar
    ├── flag
    ├── fmt
    ├── go
    ├── go.mod
    ├── go.sum
    ├── hash
    ├── html
    ├── image
    ├── index
    ├── internal
    ├── io
    ├── iostest.bash
    ├── log
    ├── make.bash
    ├── make.bat
    ├── make.rc
    ├── math
    ├── mime
    ├── naclmake.bash
    ├── nacltest.bash
    ├── net
    ├── os
    ├── path
    ├── plugin
    ├── race.bash
    ├── race.bat
    ├── reflect
    ├── regexp
    ├── run.bash
    ├── run.bat
    ├── run.rc
    ├── runtime
    ├── sort
    ├── strconv
    ├── strings
    ├── sync
    ├── syscall
    ├── testdata
    ├── testing
    ├── text
    ├── time
    ├── unicode
    ├── unsafe
    └── vendor
 
52 directories, 24 files
```

**Comment by dhruvrauthan** [comment]
Hey @i-prudnikov ,

The output of running ./prepareGoRoot.sh is now:

```
Reporting variables
goRoot => '/usr/lib/go-1.16'
goHostOS => 'linux'
goHostArch => 'amd64'
installRace => '1'
localGoRoot => './.GOROOT'
===============
cp: target './.GOROOT/src/' is not a directory
```

The contents of .GOROOT/ are:

<img width="145" alt="Screen Shot 2021-04-02 at 8 20 10 PM" src="https://user-images.githubusercontent.com/51470568/113426269-db8fca80-93f0-11eb-8da6-d78f458006f7.png">

I believe the highlighting of src indicates that it is a problem with the symlink (https://superuser.com/questions/543397/what-does-it-mean-a-red-filename-shown-with-black-background)

Removing src and running prepareGoRoot.sh again creates a broken link again.

**Comment by i-prudnikov** [comment]
Thanks for trying it out, as I see you have go 1.16, so it means that the structure of GOROOT folder is different from go 1.13. I've never tested it against anything except go 1.13
So, in order to proceed, you have 2 options:
1. Try it out against go 1.13, highly likely should work.
2.Wait util I try to fix it to work with go 1.16  (there is a possibility that it would not work).

Also I can share with you compiled (for Linux) binary or docker container.

**Comment by i-prudnikov** [comment]
Hello @dhruvrauthan , I've been digging a bit, looks like `/usr/lib/go-1.16/src` is symlink in your case.
Anyway, I've just extended the script to support go 1.16 (use `v1.0.3` tag), there should be a different patch.
Also I've add extensive logging int the script please run and show me the output.
Also would be very useful to have a look on a structure of your `/usr/lib/go-1.16`.

TO sum up, if you still have problems building it, here the workaround I recommend - to built it in official golang continer, and just copy the binary back from container.
I.E.:
```
docker run -it --rm -v /<PATH_TO_YOUR_LOCAL_COPY_OF_REPO>:/esni-rev-proxy golang:1.13-alpine3.12
#Inside container:
cd /esni-rev-proxy
./prepareGoRoot.sh
export GOROOT=$(pwd)/.GOROOT
go build
```
I've just checked against 2 images  golang:1.13-alpine3.12 and  golang:1.16-alpine3.12 - both works well.

Here complete output:
```
docker run -it --rm -v /Users/ilya.prudnikov/DevNS/src/github.com/devopsext/esni-rev-proxy:/esni-rev-proxy golang:1.16-alpine3.12
Unable to find image 'golang:1.16-alpine3.12' locally
1.16-alpine3.12: Pulling from library/golang
532819f3e44c: Pull complete
93cbbf235a55: Pull complete
e13f184a0596: Pull complete
ab7b5689fa67: Pull complete
e39c333bd790: Pull complete
Digest: sha256:4aed63f73afd82a94b2ddf30f8853d36de5528e49029706c7f6104ca8686602b
Status: Downloaded newer image for golang:1.16-alpine3.12

/go # cd /esni-rev-proxy/

/esni-rev-proxy # ./prepareGoRoot.sh
===============
Reporting variables:
goVersion => 'go1.16'
goRoot => '/usr/local/go'
goHostOS => 'linux'
goHostArch => 'amd64'
installRace => '1'
localGoRoot => './.GOROOT'
===============
Setting up symlink to /usr/local/go/bin
Copying up /usr/local/go/src to ./.GOROOT/
Patching './.GOROOT/src/' with './.patch_1.16/src/*'
Copying '/usr/local/go/pkg/linux_amd64' to './.GOROOT/pkg/'
Adding symlink to  './.GOROOT/pkg/include'
Adding symlink to  './.GOROOT/pkg/tool'

/esni-rev-proxy # export GOROOT=$(pwd)/.GOROOT

/esni-rev-proxy # go build
go: downloading github.com/paulbellamy/ratecounter v0.2.0
go: downloading github.com/prometheus/client_golang v1.5.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.9.1
go: downloading github.com/prometheus/procfs v0.0.8
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/cloudflare/sidh v0.0.0-20190228162259-d2f0f90e08aa
go: downloading github.com/henrydcase/nobs v0.0.0-20200305111951-7d891c7eb892

/esni-rev-proxy # ls -la ./esni-rev-proxy
-rwxr-xr-x    1 root     root      10592984 Apr 10 19:11 ./esni-rev-proxy

/esni-rev-proxy # ./esni-rev-proxy
2021/04/10 19:11:58 Upstream URL is not set

/esni-rev-proxy #
```

**Comment by i-prudnikov** [comment]
@dhruvrauthan, also I've added docker file and precompiled binary with CGO_ENABLED=0 for linux and darwin. I guess this should work for you. Have a look here: https://github.com/devopsext/esni-rev-proxy/releases/tag/v1.0.3

**Comment by dhruvrauthan** [comment]
Hello @i-prudnikov 

Thank you very much for trying to help me out with this issue. Your latest patch helped me out a lot with progressing further.

I am trying to run this proxy in front of an Apache2 webserver. My server is listening on port 443 since my test website has HTTPS enabled, in order to test ESNI. Now the reverse proxy gives this error while trying to start it

```
sudo ./esni-rev-proxy -b 0.0.0.0:443 -esni-keys ~/test/test2/esnitool/esni.pub -esni-private ~/test/test2/esnitool/esni -cert "test.siegelucent.tech:/etc/apache2/testsiegelucenttech.key:/etc/apache2/testsiegelucenttech.crt" -upstream https://test.siegelucent.tech -showaccesslog
2021/04/15 08:07:03 Default esniRevProxy cert/key pair would be sourced from test.siegelucent.tech:/etc/apache2/testsiegelucenttech.key:/etc/apache2/testsiegelucenttech.crt
2021/04/15 08:07:03 Starting esni reverse proxy...
2021/04/15 08:07:03 ListenAndServeTLS(): listen tcp 0.0.0.0:443: bind: address already in use
```

I believe that this error is coming up since Apache2 is also running on the same port. However if I stop the webserver to free up the port, the website won't load even if the reverse-proxy works

Do you have any idea what might be a fix for this issue?

Also, I must mention that it seems that my golang installation has been botched up somehow in my Linux VM and reinstalling it did not help. So, I compiled the binaries inside the docker container and copied them to the host (my VM) and ran the reverse-proxy from there, since my Apache2 webserver is set up in the VM.

**Comment by i-prudnikov** [comment]
Hello @dhruvrauthan, ok, finally you can compile it. 
I suppose to close this thread and could you please open another thread regarding running and configuration of the esni-rev-proxy with your question.
